kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resiliency-cr
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "patch", "list"]
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: resiliency
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resiliency-sa
  namespace: resiliency
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resiliency-crb
subjects:
  - kind: ServiceAccount
    name: resiliency-sa
    namespace: resiliency
roleRef:
  kind: ClusterRole
  name: resiliency-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: resilience-cronjob
  namespace: resiliency
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: resiliency-sa
          containers:
          - name: job
            image: abesharphpe/resiliencypod:v3
